-- ==============================================================================
-- Dust and Dazzle: Seed Data (16 Placeholder Chapters)
-- ==============================================================================

INSERT INTO public.stories (
    slug, title, subtitle, chapter_label, order_index, year, visibility, reading_time, excerpt, content_html, cover_image_url, image_caption
) VALUES
(
    'chapter-1-the-ancestral-soil',
    '[Placeholder] Chapter I: The Ancestral Soil',
    'Tales from the Northern Plains',
    'Chapter I',
    1,
    '1972',
    'published',
    '6 min read',
    '[Placeholder Excerpt: An archival vignette exploring the golden twilight of a rural Awadh courtyard and memories etched in sun-dried earth.]',
    '<p class="drop-cap-paragraph"><span class="drop-cap">I</span>[Sample Placeholder Opening Passage: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.]</p><p>[Sample Placeholder Section: Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.]</p><blockquote>"[Sample Placeholder Quote: Under the ancient banyan canopy, time slowed to the rhythm of afternoon dust.]"</blockquote><p>[Sample Placeholder Paragraph: Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.]</p><p>[Sample Placeholder Conclusion: Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.]</p>',
    '/images/sample-banyan.png',
    '[Placeholder Archival Plate: Village pond under twilight, c. 1970s]'
),
(
    'chapter-2-the-clay-diya',
    '[Placeholder] Chapter II: The Clay Diya',
    'Flickering lights in the monsoon courtyard',
    'Chapter II',
    2,
    '1974',
    'published',
    '8 min read',
    '[Placeholder Excerpt: The warmth of oil lamps during rainy evenings in the verandah.]',
    '<p class="drop-cap-paragraph"><span class="drop-cap">T</span>[Sample Placeholder Opening: At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.]</p><p>[Sample Placeholder Paragraph: Similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.]</p>',
    NULL,
    NULL
),
(
    'chapter-3-morning-train-to-lucknow',
    '[Placeholder] Chapter III: Morning Train to Lucknow',
    'Between steam, smoke, and brass tiffin carriers',
    'Chapter III',
    3,
    '1978',
    'published',
    '7 min read',
    '[Placeholder Excerpt: Journeys across rural rail crossings into the bustling provincial capital.]',
    '<p class="drop-cap-paragraph"><span class="drop-cap">W</span>[Sample Placeholder Opening: Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.]</p><p>[Sample Placeholder Paragraph: Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.]</p>',
    NULL,
    NULL
),
(
    'chapter-4-the-old-library-at-dusk',
    '[Placeholder] Chapter IV: The Old Library at Dusk',
    'Pages yellowed by Awadh humidity',
    'Chapter IV',
    4,
    '1981',
    'published',
    '9 min read',
    '[Placeholder Excerpt: Encounters with classical Urdu poetry and aged fountain pens.]',
    '<p class="drop-cap-paragraph"><span class="drop-cap">O</span>[Sample Placeholder Opening: Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.]</p>',
    NULL,
    NULL
),
(
    'chapter-5-city-of-glass-and-concrete',
    '[Placeholder] Chapter V: City of Glass and Concrete',
    'Arrival in the urban metropolis',
    'Chapter V',
    5,
    '1985',
    'published',
    '10 min read',
    '[Placeholder Excerpt: The transition from dust-laden village footpaths to high-rise avenues.]',
    '<p class="drop-cap-paragraph"><span class="drop-cap">A</span>[Sample Placeholder Opening: Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue.]</p>',
    NULL,
    NULL
),
(
    'chapter-6-shadows-on-the-verandah',
    '[Placeholder] Chapter VI: Shadows on the Verandah',
    'Conversations overheard in the quiet hours',
    'Chapter VI',
    6,
    '1988',
    'published',
    '5 min read',
    '[Placeholder Excerpt: Evening dialogues and village legends passed across generations.]',
    '<p class="drop-cap-paragraph"><span class="drop-cap">T</span>[Sample Placeholder Text: Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus.]</p>',
    NULL,
    NULL
),
(
    'chapter-7-the-brass-compass',
    '[Placeholder] Chapter VII: The Brass Compass',
    'Navigating unfamiliar crossroads',
    'Chapter VII',
    7,
    '1991',
    'published',
    '6 min read',
    '[Placeholder Excerpt: Small heirlooms carried through decades of migration.]',
    '<p class="drop-cap-paragraph"><span class="drop-cap">I</span>[Sample Placeholder Text: Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero.]</p>',
    NULL,
    NULL
),
(
    'chapter-8-monsoon-letters',
    '[Placeholder] Chapter VIII: Monsoon Letters',
    'Postcards delivered across flooded gullies',
    'Chapter VIII',
    8,
    '1994',
    'published',
    '7 min read',
    '[Placeholder Excerpt: Handwritten correspondence and the scent of damp inland envelope paper.]',
    '<p class="drop-cap-paragraph"><span class="drop-cap">D</span>[Sample Placeholder Text: Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales.]</p>',
    NULL,
    NULL
),
(
    'chapter-9-market-of-spices-and-copper',
    '[Placeholder] Chapter IX: Market of Spices and Copper',
    'Sounds and merchants of the old chowk',
    'Chapter IX',
    9,
    '1997',
    'published',
    '8 min read',
    '[Placeholder Excerpt: The bustling lanes where every seller carried a generational story.]',
    '<p class="drop-cap-paragraph"><span class="drop-cap">E</span>[Sample Placeholder Text: Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.]</p>',
    NULL,
    NULL
),
(
    'chapter-10-whispers-in-the-wheatfield',
    '[Placeholder] Chapter X: Whispers in the Wheatfield',
    'Winter harvest at dawn',
    'Chapter X',
    10,
    '2000',
    'published',
    '6 min read',
    '[Placeholder Excerpt: The first golden cut of crop and morning mist rising from the canal.]',
    '<p class="drop-cap-paragraph"><span class="drop-cap">T</span>[Sample Placeholder Text: Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim.]</p>',
    NULL,
    NULL
),
(
    'chapter-11-the-tea-stall-philosophers',
    '[Placeholder] Chapter XI: The Tea Stall Philosophers',
    'Politics, cricket, and chai on wooden benches',
    'Chapter XI',
    11,
    '2003',
    'published',
    '9 min read',
    '[Placeholder Excerpt: Daily assemblies where the fate of nations was debated over hot cardamom tea.]',
    '<p class="drop-cap-paragraph"><span class="drop-cap">E</span>[Sample Placeholder Text: Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus.]</p>',
    NULL,
    NULL
),
(
    'chapter-12-flight-above-the-clouds',
    '[Placeholder] Chapter XII: Flight Above the Clouds',
    'Looking down upon divided borders',
    'Chapter XII',
    12,
    '2007',
    'published',
    '7 min read',
    '[Placeholder Excerpt: A first aerial glance at the vast geography of home.]',
    '<p class="drop-cap-paragraph"><span class="drop-cap">F</span>[Sample Placeholder Text: Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum.]</p>',
    NULL,
    NULL
),
(
    'chapter-13-the-craftsman-of-clay',
    '[Placeholder] Chapter XIII: The Craftsman of Clay',
    'Hands that shaped water pots and festival idols',
    'Chapter XIII',
    13,
    '2012',
    'published',
    '8 min read',
    '[Placeholder Excerpt: An ode to the village potter whose wheel turned before sunrise.]',
    '<p class="drop-cap-paragraph"><span class="drop-cap">H</span>[Sample Placeholder Text: Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi.]</p>',
    NULL,
    NULL
),
(
    'chapter-14-bridges-of-the-gomti',
    '[Placeholder] Chapter XIV: Bridges of the Gomti',
    'Reflections on the moving river',
    'Chapter XIV',
    14,
    '2016',
    'published',
    '6 min read',
    '[Placeholder Excerpt: Evening walks along the heritage riverfront in summer.]',
    '<p class="drop-cap-paragraph"><span class="drop-cap">R</span>[Sample Placeholder Text: Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus.]</p>',
    NULL,
    NULL
),
(
    'chapter-15-the-return-to-the-threshold',
    '[Placeholder] Chapter XV: The Return to the Threshold',
    'Revisiting the ancestral doorway',
    'Chapter XV',
    15,
    '2020',
    'published',
    '11 min read',
    '[Placeholder Excerpt: Unlocking the wooden latch after twenty seasons away.]',
    '<p class="drop-cap-paragraph"><span class="drop-cap">U</span>[Sample Placeholder Text: Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante.]</p>',
    NULL,
    NULL
),
(
    'chapter-16-dazzle-in-the-dust',
    '[Placeholder] Chapter XVI: Dazzle in the Dust',
    'A reconciliation of memory, place, and time',
    'Chapter XVI',
    16,
    '2024',
    'published',
    '12 min read',
    '[Placeholder Excerpt: Closing reflections on the dual tapestry of village quietude and urban ambition.]',
    '<p class="drop-cap-paragraph"><span class="drop-cap">A</span>[Sample Placeholder Concluding Chapter: Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc.]</p><blockquote>"[Sample Placeholder Epigraph: The dust has settled, yet in every grain, a spark of dazzle remains.]"</blockquote><p>[Sample Placeholder Epilogue: Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Praesent adipiscing. Phasellus ullamcorper ipsum rutrum nunc.]</p>',
    NULL,
    NULL
)
ON CONFLICT (slug) DO NOTHING;
